# Generated by Django 5.2.5 on 2026-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cliente_dni_alter_cliente_id_alter_cliente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
    ]
