# Generated by Django 5.2.5 on 2026-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_direccion_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
    ]
