# Generated by Django 6.0.5 on 2026-06-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_cliente_id_alter_direccion_id'),
        ('users', '0013_direccion_referencia'),
    ]

    operations = [
    ]
