# Generated by Django 6.0.2 on 2026-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_gasto_id_alter_pago_id_alter_pedido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_info',
            field=models.TextField(blank=True, help_text='Información de dirección del envío', null=True),
        ),
    ]
