# Generated by Django 5.2.5 on 2026-05-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_gasto_id_alter_pago_id_alter_pedido_id_and_more'),
        ('pedidos', '0006_pedido_direccion_info'),
    ]

    operations = [
    ]
