# Generated by Django 5.2.5 on 2026-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_merge_20260507_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='calle_numero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('local', 'Retiro en Local (Gratis)'), ('domicilio', 'Envío a Domicilio')], default='local', max_length=20),
        ),
    ]
