# Generated by Django 5.2.5 on 2026-05-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_calle_numero_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('aceptado', 'Pago aceptado'), ('en_preparacion', 'En preparación'), ('listo_retirar', 'Listo para retirar'), ('preparando_envio', 'Preparando envío'), ('enviado', 'Paquete enviado'), ('entregado', 'Entregado'), ('rechazado', 'Pago rechazado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendiente', max_length=20),
        ),
    ]
