# Generated by Django 6.0.5 on 2026-05-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_gasto_id_alter_pago_id_alter_pedido_id_and_more'),
        ('pedidos', '0009_alter_pedido_estado'),
    ]

    operations = [
    ]
