# Generated by Django 5.2.5 on 2026-05-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_merge_20260511_1924'),
        ('pedidos', '0009_alter_pedido_estado'),
    ]

    operations = [
    ]
