# Generated by Django 5.2.5 on 2026-05-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_merge_20260513_0111'),
        ('productos', '0017_alter_variantecolor_id'),
        ('users', '0008_alter_cliente_id_alter_direccion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_local', to='users.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaLocalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.variante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.ventalocal')),
            ],
        ),
    ]
