# Generated by Django 5.2.5 on 2026-05-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_ventalocal_ventalocalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalocal',
            name='estado_pago',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PARCIAL', 'Parcial')], default='PAGADO', max_length=20),
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PagoVentaLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pedidos.ventalocal')),
            ],
        ),
    ]
