# Generated by Django 5.2.5 on 2026-05-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_merge_20260513_1938'),
        ('pedidos', '0012_ventalocal_estado_pago_ventalocal_monto_pagado_and_more'),
    ]

    operations = [
    ]
