# Generated by Django 5.2.5 on 2026-05-15 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_gasto_id_alter_pago_id_alter_pedido_id_and_more'),
        ('users', '0011_alter_cliente_id_alter_direccion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.direccion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_correo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_correo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('local', 'Retiro en Local (Gratis)'), ('flex', 'Envío Flex'), ('domicilio', 'Envío a Domicilio')], default='local', max_length=20),
        ),
    ]
