# Generated by Django 5.2.5 on 2026-05-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_correo_pedido_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_flex', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flex_gratis', models.BooleanField(default=False)),
                ('zonas_flex', models.TextField(help_text='Separar zonas con coma')),
            ],
        ),
    ]
