# Generated by Django 5.2.5 on 2026-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_configuracionenvio_flex_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_presencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
    ]
