# Generated by Django 6.0.5 on 2026-06-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_alter_configuracionenvio_id_alter_gasto_id_and_more'),
        ('pedidos', '0025_envio_pedido_configuracion_correo'),
    ]

    operations = [
    ]
