# Generated by Django 6.0.6 on 2026-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0026_merge_20260620_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionenvio',
            name='correo_a_coordinar',
            field=models.BooleanField(default=False, help_text='Mostrar "A coordinar" en lugar de precio fijo para envío por correo'),
        ),
        migrations.AlterField(
            model_name='configuracionpago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enviopedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('mercado_pago_qr', 'Mercado Pago QR'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plancuotasmercadopago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ventalocal',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('mercado_pago_qr', 'Mercado Pago QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
    ]
