# Generated by Django 6.0.6 on 2026-06-20 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_configuracionenvio_correo_a_coordinar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta/Posnet'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
