# Generated by Django 5.2.5 on 2026-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0029_alter_configuracionenvio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviopedido',
            name='sucursal_id',
            field=models.CharField(blank=True, help_text='ID de sucursal para PAQ.AR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_correo_id',
            field=models.CharField(blank=True, help_text='ID de la sucursal para PAQ.AR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionenvio',
            name='correo_activo',
            field=models.BooleanField(default=False, help_text='Mostrar Correo Argentino como opcion en el checkout'),
        ),
        migrations.AlterField(
            model_name='enviopedido',
            name='proveedor',
            field=models.CharField(choices=[('correo_argentino', 'Correo Argentino'), ('flex', 'Envio Flex')], max_length=30),
        ),
    ]
