# Generated by Django 5.2.5 on 2026-08-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0030_add_sucursal_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionenvio',
            name='flex_gratis_activo',
            field=models.BooleanField(default=False, help_text='Mostrar Envío Flex Gratis en el checkout'),
        ),
        migrations.AddField(
            model_name='configuracionenvio',
            name='zonas_flex_gratis',
            field=models.TextField(blank=True, help_text='Zonas para Envío Flex Gratis. Separar con coma.'),
        ),
        migrations.AlterField(
            model_name='configuracionenvio',
            name='correo_a_coordinar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracionenvio',
            name='correo_activo',
            field=models.BooleanField(default=False, help_text='Mostrar Correo Argentino en el checkout (precio automático)'),
        ),
        migrations.AlterField(
            model_name='configuracionenvio',
            name='flex_activo',
            field=models.BooleanField(default=True, help_text='Mostrar Envío Flex (con precio) en el checkout'),
        ),
        migrations.AlterField(
            model_name='configuracionenvio',
            name='zonas_flex',
            field=models.TextField(blank=True, help_text='Zonas para Envío Flex con precio. Separar con coma.'),
        ),
    ]
