# Generated by Django 5.2.5 on 2026-08-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_split_flex_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('local', 'Retiro en Local (Gratis)'), ('flex_gratis', 'Envio Flex Gratis'), ('flex', 'Envio Flex'), ('correo', 'Envio por Correo')], default='local', max_length=20),
        ),
    ]
