# Generated by Django 6.1 on 2026-09-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0031_add_retencion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionEnvioFlex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_gratis', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('zonas', models.TextField(blank=True, help_text='Separar zonas con coma. Ej: CABA, La Plata, Quilmes')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar en checkout')),
            ],
            options={
                'verbose_name': 'Opción de Envío Flex',
                'verbose_name_plural': 'Opciones de Envío Flex',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='opcion_flex',
            field=models.ForeignKey(blank=True, help_text='Opción de Flex seleccionada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.opcionenvioflex'),
        ),
    ]
