# Generated by Django 6.1 on 2026-09-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0032_add_opcion_envio_flex'),
        ('productos', '0030_alter_categoria_id_alter_categoriaorden_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField(default=1)),
                ('cantidad_entregada', models.PositiveIntegerField(default=1)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='pedidos.pedido')),
                ('producto_devuelto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_devueltos', to='productos.producto', verbose_name='Producto devuelto')),
                ('producto_entregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_entregados', to='productos.producto', verbose_name='Producto entregado')),
                ('variante_devuelta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_devueltos', to='productos.variante', verbose_name='Variante devuelta')),
                ('variante_entregada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_entregados', to='productos.variante', verbose_name='Variante entregada')),
                ('venta_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='pedidos.ventalocal')),
            ],
            options={
                'verbose_name': 'Cambio',
                'verbose_name_plural': 'Cambios',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('usada', 'Usada'), ('vencida', 'Vencida')], default='vigente', max_length=20)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='pedidos.pedido', verbose_name='Pedido de origen')),
                ('pedido_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_usadas', to='pedidos.pedido', verbose_name='Pedido donde se usó')),
                ('venta_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='pedidos.ventalocal', verbose_name='Venta local de origen')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
            },
        ),
    ]
