# Generated by Django 5.2.5 on 2026-08-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0032_alter_pedido_metodo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tarifa_correo_nombre',
            field=models.CharField(blank=True, help_text='Nombre del servicio de envío seleccionado', max_length=100, null=True),
        ),
    ]
