# Generated by Django 6.1.2 on 2026-10-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0033_add_tarifa_correo_nombre'),
        ('pedidos', '0033_cambio_notacredito'),
    ]

    operations = [
    ]
