# Generated by Django 6.1.2 on 2026-10-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0034_merge_20261006_1322'),
        ('productos', '0032_alter_categoria_id_alter_categoriaorden_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.variante'),
        ),
        migrations.AlterField(
            model_name='ventalocalitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='ventalocalitem',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.variante'),
        ),
    ]
