# Generated by Django 6.1.2 on 2026-10-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0035_proteger_items_de_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('usada', 'Usada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='vigente', max_length=20),
        ),
        migrations.CreateModel(
            name='NotaCreditoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.notacredito')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='pedidos.pedidoitem')),
            ],
        ),
    ]
