# Generated by Django 6.1.2 on 2026-10-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0036_nota_credito_devoluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalocal',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventalocal',
            name='opcion_flex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_locales', to='pedidos.opcionenvioflex'),
        ),
    ]
