# Generated by Django 6.1.2 on 2026-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0037_venta_local_costo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambio',
            name='color_devuelto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cambio',
            name='color_entregado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
