from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('gestion/', views.gestion_pedidos, name='gestion_pedidos'),
    path('estadisticas/', views.estadisticas_ventas, name='estadisticas_ventas'),
    path('gastos/', views.listado_gastos, name='listado_gastos'),
    path('gastos/crear/', views.crear_gasto, name='crear_gasto'),
    path('gastos/<int:gasto_id>/eliminar/', views.eliminar_gasto, name='eliminar_gasto'),
    path('deudas/', views.listado_deudas, name='listado_deudas'),
    path('historial-cliente/<int:cliente_id>/', views.historial_cliente, name='historial_cliente'),
    path('<int:pedido_id>/', views.detalle_pedido, name='detalle_pedido'),
    path('<int:pedido_id>/ticket-cambio/', views.ticket_cambio_pedido, name='ticket_cambio_pedido'),
    path('<int:pedido_id>/ticket-envio/', views.ticket_envio_pedido, name='ticket_envio_pedido'),
    path('<int:pedido_id>/tracking/', views.actualizar_tracking_envio, name='actualizar_tracking_envio'),
    path('<int:pedido_id>/generar-etiqueta/', views.generar_etiqueta_pedido, name='generar_etiqueta_pedido'),
    path('<int:pedido_id>/editar/', views.editar_pedido, name='editar_pedido'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('confirmar/', views.confirmar_pedido, name='confirmar_pedido'),
    path('checkout/eliminar/<int:variante_id>/', views.eliminar_item_carrito, name='eliminar_item_carrito'),
    path('checkout/validar-codigo/', views.validar_codigo_descuento, name='validar_codigo_descuento'),
    path('checkout/quitar-codigo/', views.quitar_codigo_descuento, name='quitar_codigo_descuento'),
    path('checkout/cotizar-correo/', views.cotizar_correo_argentino_checkout, name='cotizar_correo_argentino'),
    path('checkout/buscar-sucursales/', views.buscar_sucursales_correo, name='buscar_sucursales_correo'),
    path('crear-pago/', views.crear_pago, name='crear_pago'),
    path('pago-exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('estado/<int:pedido_id>/',views.estado_pedido, name='estado_pedido'),
    path('mis-pedidos/',views.mis_pedidos,name='mis_pedidos'),
    path('aumentar-cantidad/<int:variante_id>/',views.aumentar_cantidad, name='aumentar_cantidad'),
    path('disminuir-cantidad/<int:variante_id>/',views.disminuir_cantidad,name='disminuir_cantidad'),
    path('actualizar-estado/<int:pedido_id>/',views.actualizar_estado_pedido,name='actualizar_estado_pedido'),
    path('ventas-presenciales/',views.ventas_presenciales,name='ventas_presenciales'),
    path('registrar-venta-local/',views.registrar_venta_local,name='registrar_venta_local'),
    path('detalle-venta/<int:venta_id>/',views.detalle_venta_local,name='detalle_venta_local'),
    path('venta-local/<int:venta_id>/ticket-cambio/', views.ticket_cambio_venta_local, name='ticket_cambio_venta_local'),
    path('venta-local/<int:venta_id>/ticket-envio/', views.ticket_envio_venta_local, name='ticket_envio_venta_local'),
    path('registrar-pago/<int:venta_id>/',views.registrar_pago_venta,name='registrar_pago_venta'),
    path('registrar-pago-pedido/<int:pedido_id>/',views.registrar_pago_pedido,name='registrar_pago_pedido'),
    path('envios/configurar/', views.configurar_envios, name='configurar_envios'),
    path('pagos/configurar/', views.configurar_pagos, name='configurar_pagos'),
    path('transferencia/<int:pedido_id>/enviar-comprobante/', views.enviar_comprobante_transferencia, name='enviar_comprobante_transferencia'),
]
