# Generated by Django 6.0.2 on 2026-05-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_consulta_id_alter_temaconsulta_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temaconsulta',
            options={'verbose_name': 'Tema de consulta', 'verbose_name_plural': 'Temas de consulta'},
        ),
        migrations.AddField(
            model_name='temaconsulta',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
