# Generated by Django 6.0.2 on 2026-05-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_temaconsulta_options_temaconsulta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['orden', 'created_at'], 'verbose_name': 'Pregunta frecuente', 'verbose_name_plural': 'Preguntas frecuentes'},
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='fecha',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='consulta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='pregunta',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='respuesta',
            field=models.TextField(verbose_name='Respuesta'),
        ),
    ]
