# Generated by Django 6.0.5 on 2026-05-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_consulta_id_alter_temaconsulta_id'),
        ('consultas', '0007_cambio_modelo_faq'),
    ]

    operations = [
    ]
