# Generated by Django 6.0.5 on 2026-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_merge_20260511_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
