# Generated by Django 5.2.5 on 2026-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_alter_consulta_id_alter_temaconsulta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
