# Generated by Django 6.0.5 on 2026-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideCarrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrousel/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True, help_text='URL opcional al hacer clic')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide del Carrousel',
                'verbose_name_plural': 'Slides del Carrousel',
                'ordering': ['orden', '-created_at'],
            },
        ),
    ]
