# Generated by Django 6.0.5 on 2026-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_slidecarrousel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidecarrousel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
