# Generated by Django 6.0.6 on 2026-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_slidecarrousel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Nueva colección', help_text='Texto pequeño encima del título', max_length=100)),
                ('titulo_linea1', models.CharField(default='Elegancia', help_text='Primera línea del título', max_length=100)),
                ('titulo_linea2', models.CharField(default='que se siente', help_text='Segunda línea del título (en cursiva)', max_length=100)),
                ('subtitulo', models.CharField(default='Descubrí prendas únicas, pensadas para vos.', max_length=255)),
                ('texto_cta', models.CharField(default='Ver colección', help_text='Texto del botón', max_length=50)),
                ('link_cta', models.CharField(default='#catalogo', help_text='URL del botón', max_length=255)),
                ('color_fondo', models.CharField(default='#1a1612', help_text='Color de fondo (hex)', max_length=20)),
                ('color_texto', models.CharField(default='#ffffff', help_text='Color del texto (hex)', max_length=20)),
                ('color_acento', models.CharField(default='#b8922a', help_text='Color de acento/decoración (hex)', max_length=20)),
                ('fuente_titulo', models.CharField(choices=[('Cormorant Garamond', 'Cormorant Garamond (elegante)'), ('Playfair Display', 'Playfair Display (clásica)'), ('DM Sans', 'DM Sans (moderna)')], default='Cormorant Garamond', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Hero',
                'verbose_name_plural': 'Configuración del Hero',
            },
        ),
    ]
