# Generated by Django 6.0.6 on 2026-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_configuracionhero'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhero',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo opcional (reemplaza el color)', null=True, upload_to='hero/'),
        ),
    ]
