# Generated by Django 5.2.5 on 2026-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_configuracionhero_imagen_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionhero',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slidecarrousel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
