# Generated by Django 5.2.5 on 2026-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
