# Generated by Django 5.2.5 on 2026-05-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0006_alter_carrito_id_alter_carritoitem_id'),
        ('users', '0008_alter_cliente_id_alter_direccion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='session_id',
            field=models.CharField(blank=True, help_text='ID de sesión para carritos de invitados', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cliente'),
        ),
    ]
