# Generated by Django 6.0.5 on 2026-05-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0007_alter_carrito_id_alter_carritoitem_id'),
        ('carritos', '0007_carrito_session_id_alter_carrito_cliente'),
    ]

    operations = [
    ]
