# Generated by Django 6.0.5 on 2026-06-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0010_alter_carrito_id_alter_carritoitem_id'),
        ('carritos', '0010_carritoitem_color_nombre'),
    ]

    operations = [
    ]
