# Generated by Django 5.2.5 on 2026-08-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0012_alter_carrito_id_alter_carritoitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
