# Generated by Django 5.2.5 on 2026-03-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='medidas',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='productos.tipomedida'),
        ),
    ]
