# Generated by Django 5.2.5 on 2026-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_tipomedida_proveedor_medidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='informacion_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
