# Generated by Django 5.2.5 on 2026-03-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_proveedor_informacion_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='medidas',
        ),
    ]
