# Generated by Django 5.2.5 on 2026-03-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoria_id_alter_categoriaorden_id_and_more'),
        ('productos', '0006_remove_proveedor_medidas'),
    ]

    operations = [
    ]
