# Generated by Django 5.2.5 on 2026-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_imagen_producto_avios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_tecnica',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fichas/'),
        ),
    ]
