# Generated by Django 5.2.5 on 2026-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_imagen_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='talle',
            field=models.CharField(max_length=50),
        ),
    ]
