# Generated by Django 5.2.5 on 2026-04-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_variante_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.talle'),
        ),
    ]
