# Generated by Django 5.2.5 on 2026-05-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_alter_variantecolor_id'),
        ('productos', '0018_alter_categoria_id_alter_categoriaorden_id_and_more'),
    ]

    operations = [
    ]
