# Generated by Django 6.0.5 on 2026-06-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_alter_categoria_id_alter_categoriaorden_id_and_more'),
        ('productos', '0023_producto_tamano_paquete'),
    ]

    operations = [
    ]
