# Generated by Django 6.0.6 on 2026-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_merge_20260620_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='detalle_etiqueta',
            field=models.CharField(blank=True, help_text='Info adicional de etiqueta (ej: Prelavado, Tela premium)', max_length=255, null=True),
        ),
    ]
