# Generated by Django 5.2.5 on 2026-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_alter_categoria_id_alter_categoriaorden_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='codigo_hex',
            field=models.CharField(default='#888888', max_length=7),
        ),
    ]
