# Generated by Django 5.2.5 on 2026-08-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_alter_categoria_id_alter_categoriaorden_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='limite_usos',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de veces que se puede usar el código. Dejar vacío para ilimitado.', null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='usos_actuales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano_paquete',
            field=models.CharField(choices=[('chico', 'Chico - accesorios, remeras, tops'), ('mediano', 'Mediano - buzos, pantalones, vestidos'), ('grande', 'Grande - camperas, zapatillas, abrigos')], default='mediano', max_length=20),
        ),
    ]
