# Generated by Django 5.2.5 on 2026-08-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0030_add_limite_usos_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantecolor',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
