# Generated by Django 6.1.2 on 2026-10-09 15:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0033_proteger_productos_de_subcategoria_y_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El precio tiene que ser mayor a 0.')]),
        ),
    ]
